# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-29 16:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Summary',
            new_name='Comment',
        ),
    ]
