# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 16:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_grade_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='position',
        ),
    ]
