# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_remove_grade_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='position',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
